---
- block:
  - name: check that deploy user is defined
    fail: msg="deploy_user is not defined"
    when: deploy_user is not defined or not deploy_user

  - name: set up deployment account
    user: name={{ deploy_user }} comment="Deployment Account" state=present shell=/bin/bash

  become: true
  become_user: root
