---
- name: unlock role dependencies
  set_fact:
    laravel_api_code_unlock_dep_roles: true   # shame on me for such ugly trick

- include_tasks: deployer-user.yml
  when: create_deploy_user and deploy_user != 'root'

- include_tasks: deploy-dependencies.yml
  tags: server-provision

- include_tasks: code-deploy.yml
  tags: code-deploy
