---
- hosts: all
  tasks: []

- name: Converge
  hosts: ansible
  vars:
    deploy_user: deploy
  pre_tasks:
    # prepare access to mysql and ensure it's up
    - name: set mysql host
      set_fact:
        mysql_host: "{{ hostvars['mysql']['ansible_default_ipv4']['address'] }}"
    - name: wait for mysql to be up
      shell:
        while [ ${x:-0} -lt 120 ]; do
          nc -z {{ mysql_host }} 3306 && exit 0;
          sleep 1;
          x=$((${x:-0} + 1));
        done ;
        exit 1;
      args:
        executable: /bin/bash
      tags:
        - skip_ansible_lint
  roles:
    - role: ushahidi.common
      firewall_disabled: True
    - role: ushahidi.php
      php_minor_version: "5.6"
    - role: ansible-laravel-api-code
      laravel_api_base_path: /var/www/app
      laravel_api_repo_url: https://github.com/tuxpiper/laravel-realworld-example-app.git
      laravel_api_repo_version: master
      laravel_api_dotenv_sample: .env.example
      laravel_api_composer_dev_pkgs: yes
      laravel_api_env:
        APP_KEY: "testOplomo"
        DB_HOST: "{{ mysql_host }}"
        DB_DATABASE: "test"
        DB_USERNAME: "test"
        DB_PASSWORD: "test"
